name: reqruit_manager
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # ログイン永続化用
  shared_preferences: ^0.5.7+2

  # 状態管理
  provider: ^4.1.2

  # HUD用のプラグイン
  bmprogresshud: ^0.0.7

  # BSDライセンスなのでちゃんと調べる
  page_transition: ^1.1.5

  # チュートリアルのやつ
  flutter_overboard: ^1.1.5

  # fireBaseのAuth認証
  firebase_auth: ^0.16.1

  # fireStore
  cloud_firestore: ^0.13.6

  # アルバム開くプラグイン
  image_picker: ^0.6.7+1

  # fireStorage
  firebase_storage: ^3.1.6

  # アプリアイコンを生成するプラグイン
  flutter_launcher_icons: ^0.7.3

  # datePicker
  flutter_datetime_picker: ^1.3.8

  # 外部ブラウザに遷移
  url_launcher: ^5.4.11

  # progressIndicator
  percent_indicator: ^2.1.5

  # push
  firebase_messaging: ^6.0.16

  # googleAuth
  google_sign_in: ^4.5.1

  # 必要かどうか検討
  firebase_core: ^0.4.5

  # appleSignIn
  apple_sign_in: ^0.1.0

  # appleSignInをios13のみで使用する用
  device_info: ^0.4.2+4

  # 住所から緯度・経度を計算するためのもの
  geocoder: ^0.2.1

flutter_icons:
#  image_path: "assets/app_icons/ios_icon.png"
  image_path: "assets/app_icons/android_icon.png"
#  ios: true
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # New Images
    - assets/images/
    - assets/icon/
    - assets/app_icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
